version: '3.8'

services:
  # DB
  db:
    image: mysql:8.0
    container_name: ${APP_NAME}-db
    volumes:
      - ./.data/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - mynetwork

networks:
  mynetwork:
    name: ${APP_NAME}-network
    driver: bridge
