#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
magenta=`tput setaf 5`
cyan=`tput setaf 6`
bold=`tput bold`
reset=`tput sgr0`

echo "🏗️👷🔦🔍 Styling, testing your code before committing 🏗️👷🔦🔍"

# Check Prettier standards
npm run check-format ||
(
  echo "${red}[Prettier Check Failed]${reset} Your code styling looks disgusting. 🤢🤮🤢🤮
    1. Run ${cyan}${bold}npm run format${reset} or ${cyan}${bold}yarn format${reset} to fix it,
    2. Add changes and try commit again."
  false;
)
echo "${green}[Prettier Check OK]${reset}"

# Check Next ESLint
npm run lint ||
(
  echo "${red}[ESLint Check Failed]${reset} Get that weak shit out of here! 😤💩❌👎
    Make the changes required above and try again."
  false; 
)
echo "${green}[ESLint Check OK]${reset}"

# Check tsconfig standards
npm run check-types ||
(
  echo "${red}[Type Check Failed]${reset} Are you seriously trying to write that? 🤡😂❌🤡
    Make the changes required above and try again."
  false;
)
echo "${green}[Type Check OK]${reset}"

# Now we can commit
echo "${green}[All Check SUCCESS]${reset} You're doing great, Babe. ✅👍🎉✅
❤️ I am committing this now ❤️\n"
